### ISSUE TITLE
general question: when modeling, should i seperate data  combination  and path combination?

### ISSUE THREAD

**Issue by dassio** [01org/fMBT#53]
just read the tutriou, it seems there is only path combination, from my understanding path and data combination should be seperated_**(in case there is one factor that is not relevent , we can just remove it and do not affect the mode actions.)**_ is there any guide lines recording to this?

**Comment by askervin** [comment]
What data will be covered by the test generator depends on

1. how you make the data is visible to the test generator

2. if the data is visible, then how you measure the ``coverage`` in the [test configuration](https://github.com/01org/fMBT/blob/master/doc/configuration.txt)

By default, fMBT test generator does not make difference between covering ``i:call Alice``, ``i:call Bob`` or ``i:play music``, although one could say that Alice and Bob are only two different data values for the same "call" action. That said, in this case the data _is_ visible to the test generator as different action names, so the generator will be able to cover both values if you measure coverage with the ``perm(x)``.

If you have several data combinations that your actions take, listing in action names quickly gets inconvenient. For instance, instead of ``i:call Alice with Skype`` and ``i:call Alice with WhatsApp``, you can make the data visible by splitting actions to a sequence of _set_ and a _do_ action. For example, ``i:callee='Alice'``, ``i:callee='Bob'``, ``i:phoneApp='Skype'``, ``i:phoneApp='WhatsApp'`` and enable running ``i:call`` whenever ``callee`` and ``phoneApp`` are set.

Example:
```
variables { callee, phoneApp }
initial_state {
    callee = 'Alice'
    phoneApp = 'Skype'
}
input "callee='Alice'", "callee='Bob'", "phoneApp='Skype'", "phoneApp='WhatsApp'" {
    body { exec input_name in globals() }
}
input "call" {}
```

And cover all call combinations with test configuration:
```
model     = aal_remote(remote_pyaal -l call.log call.aal)
adapter   = aal
heuristic = lookahead(4)
coverage  = perm(3, "i:callee.*", "i:phoneApp.*", "i:call")
```

Depending on your case, you may also want to hide the data from the fMBT test generator. You can keep the data in variables only. This also allows using libraries like random and [constraint](https://labix.org/python-constraint) for generating and deciding combinations you want to cover. You can use tags, for instance, to help fMBT test generator to track how many combinations have been covered.

**Comment by dassio** [comment]
thanks !!  this is very helpful, but i think i need to look more into it ,since  i never heard of the **constraint** way doing combinations. but could you elaborate more on the  `exec input_name in globals()` . from my understanding it just update the state vriable by executing the input name , but i dont't see this syntax in the [aal/python](https://github.com/01org/fMBT/blob/master/doc/aal_python.txt)  page. maybe it could be added to it ?

**Comment by askervin** [comment]
The exec statement is standard Python. It takes Python code (string), and optionally a namespace (dictionary) as input. Exec compiles and executes the string in the given namespace. So in this example the contents of the input_name variable is executed as Python code.

I added examples on Python ``exec`` and ``eval`` to AAL/Python documentation in commit 83d4c962b878878fb9f5ab70b2a2b0e120cc37f4.

Big thanks for your question and the improvement idea!
