### ISSUE TITLE
using multiprocessing in aal model with heuristic lookahead

### ISSUE THREAD

**Issue by dassio** [01org/fMBT#54]
i have a mode that need to create a seperate server for event receiving

```
aal "test" {
    language "python" {
        # -*- coding: utf-8 -*-
        from multiprocessing import Process
        def start_server_process():
            p_server = Process()
            p_server.start()
            return p_server
    };
    
    variables {p_server,p_server_up}
    
    initial_state {
        p_server = None
        p_server_up = False
    }
    
    adapter_exit {
        p_server.terminate()
    }
    
    #start the server in another process
    input "start_server" {
        guard {return not p_server_up}
        adapter {
            p_server = start_server_process()
            assert p_server
		}
        body { p_server_up = True}
    }
    input "another action" {
    }
}
```

when i use the default heuristic(random), this code works fine ,but when i try to use heuristic(lookahead), ,**after start_server action passed**,  an error pops up:

```
Traceback (most recent call last):
  File "C:\Python27\lib\copy.py", line 190, in deepcopy
    y = _reconstruct(x, rv, 1, memo)
  File "C:\Python27\lib\copy.py", line 334, in _reconstruct
    state = deepcopy(state, memo)
  File "C:\Python27\lib\copy.py", line 163, in deepcopy
    y = copier(x, memo)
  File "C:\Python27\lib\copy.py", line 257, in _deepcopy_dict
    y[deepcopy(key, memo)] = deepcopy(value, memo)
  File "C:\Python27\lib\copy.py", line 182, in deepcopy
    rv = reductor(2)
  File "C:\Python27\lib\multiprocessing\process.py", line 290, in __reduce__
    'Pickling an AuthenticationString object is '

Remote expected integer, got nothing
remote_pyaal error: Pickling an AuthenticationString object is disallowed for security reasons
aal remote(remote_pyaal -l test.aal.log test.aal) returned error Child process exited with code 1

heuristic error: Alg: Model:
model error:
error: Heuristic error

error
```

**Comment by askervin** [comment]
I'd recommend removing ``p_server = None`` from the initial_state block and putting it in the adapter_init block. An explanation on what's happening follows.

Variables that you initialize in the initial state block become "model variables". It means that their values are saved and restored when the lookahead heuristic simulates alternative test executions. (Lookahead needs to be able to change the values and then revert the changes in order to simulate how executing a test step would affect current state.) This works fine for simple data values (like int, float, string, set, tuple, list, dictionary and values that are constructed from these). But it does not work for data that has something complex behind it: file handles, sockets, processes, etc.

Luckily, in this example, you do not need ``p_server`` as a "model variable", as you already have ``p_server_up``. You can use it in guard and body blocks, and limit using ``p_server`` to adapter blocks only.

**Comment by dassio** [comment]
thanks . it works for me .
Quick question:  are there any guide line regarding to "model variables" and "adapter variables" such as: i should not update model variables in adapter block?

**Comment by askervin** [comment]
fMBT does not prevent updating model variables in adapter blocks or accessing adapter variables in guard or body blocks. That said, doing so is likely to cause problems in test generation when using lookahead heuristics.

In "school book model-based testing" you would keep model and adapter strictly separate. That enables lookahead heuristics to simulate long sequences that are likely to be executed as planned. It's good idea to stick with this idea as far as it is possible.

However, there are valid use cases when you may need to break the wall between model and adapter. You may want to use fMBT to make monkey testing smarter: execute test steps according what seems to be possible in the system under test. Or you may want to generate and run several hours or days long reliability tests with recovery features written in the model. (By recovery I mean logic that tries to get back to a valid state in the system under test without doing hard reset, like a user of a smartphone would dismiss crash dialogs without rebooting the phone.)
