### ISSUE TITLE
using model as an adapter only ?

### ISSUE THREAD

**Issue by dassio** [01org/fMBT#56]
i have a model with 63 actions with adapter blocks, i understand that to use the aal file as an model only , i just need to leave the apdater out in the conf file, still  it took about 12 minutes to generate the testcase with converage perm(1) .

my question is : 
can i still use the  adapter in the model with  genereated offline testcase in  the log file,  or i have to write  testcase executor code to read the offline testcase and exect it like in the fllowing(this is a simple case, i some case it may become complicated and I ended up with lot duplicate code -- one in **model adapter block** and one in **offfline testcase executor** ):
```
##########################################
# Generate and run the test.

# This is an "offline" test: test.conf does not define an
# adapter. fmbt only generates and simulates the test run. Yet nothing
# is actually executed, simulated test steps are logged.
#
# We use fmbt-log to pick up the generated test from the log. Then we
# call the corresponding test step (shell function) for each step:

fmbt test.conf | fmbt-log -f '$as' | while read teststep; do

    if eval "$teststep"; then
        echo "pass"
    else
        echo "fail"
    fi

done
```

**Comment by askervin** [comment]
There are different ways to speed up test generation:

* Use smaller lookahead depth. If any action in the model can be executed by taking at most n steps from any state, you can get optimal test by using n as a lookahead depth. Using depth greater than n only makes test generation slower.

* Instead of ``lookahead(d)`` use ``lookahead(1:d)``. This means that the lookahead heuristic goes through all sequences of length 1, then 2, ..., and finally d. But it immediately stops when it finds sequences of length x (1 <= x <= d) that increase coverage. This is likely to be a lot faster than constructing always all sequences of length n and choosing the best, but resulting test may not be as well optimized.

* Instead of ``lookahead(d)`` use ``lookahead(db)``. (Add letter "b" for "burst" right after the depth.) This makes lookahead stick with the planned sequence until it is completely consumed, and only after that plan next d steps. Again, faster test generation but possibly less optimal test.

Naturally the speed of Python code in guard and body blocks also plays a role in test generation speed.


Probably the best way to rerun a previously run (or only off-line generated) test is Method 2 in:

https://github.com/01org/fMBT/wiki/fMBT-FAQ#how-can-i-execute-test-steps-from-a-test-log

It will run initial_state, adapter_init, adapter_exit, guard and body blocks in addition to the adapter blocks. Often this is desired, because it's convenient to read model variables in adapter blocks. (Writing is not that convenient as discussed in issue #54.)
