### ISSUE TITLE
adapter questions

### ISSUE THREAD

**Issue by dassio** [01org/fMBT#59]
**questions 1:**
The adapter stack section in the adapter documents , are they corresponding  to the adapter section in configuration documents? like:

adapter_remote <---> remote(\<command\>)

adapter_mapper <----> mapper(\<filename\>)

adapter_dlopen  <---> lib(<adaptername,[filename])

**question 2:**
What is the difference between **`remote_python`** and **`remote_pyaal`**?
from my understanding remote_python is just an translation part without the aal protocol implementation, and remote_aal is **`adapter_remote`**(as in the adapter stack section in the adapters docs) that bridge the adapter  process(the aal/python file) and the fmbt process, is this correct?

**quesion 3:**
what is the difference between `aal_remote` and `remote` in the configuration file?

**Comment by askervin** [comment]
**Answer 1:** The last adapter would be adapter_dlopen <---> dlopen(filename,[adapterspec]), I think. Otherwise your mapping looks correct. You can find which source module implements which model/adapter by ``grep '"aal_remote"' src/*``.

**Answer 2:** Yep, that's pretty much it. In architecture perspective it's also worth mentioning that the same ``remote_aal`` instance can implement a model, an adapter or both model and adapter in the same process. ``remote_python`` implements only an adapter.

**Answer 3:** In fMBT perspective there is no much difference: in both cases the parameter tells how to launch a child process that  implements a model and/or an adapter. However, the runners are quite different (see ``remote_pyaal --help`` and ``remote_python --help``)

Historically fMBT and its adapter stack were born roughly a year earlier than the first thoughts about AAL/Python and AAL/C++. Gt was used as modelling language. (You can it for fun: ```fmbt-gt 'P(s, "gt:istate") -> T(s, "i:hello", s2) T(s2, "i:world", s)' | fmbt-view -```.) Due to modelling language limitations the adapter stack was designed to solve certain common issues, such as distribution of test step execution to multiple processes and devices.

Now that AAL is around, I would solve many distribution problems with a simple Python library that I would call from AAL/Python rather than using fMBT's built-in mapper/remote adapters. A custom pure-Python is easier to develop, test and debug (as it runs also without fMBT), and more flexible modify to fit your needs. But if you don't benefit from AAL's adapters, then the adapter stack offers many ways to implement your own adapter. The ``remote`` adapter lets you implement it with the programming language that is easiest to connect to your system under test.
